description = "Ada Stemmer Library"
name = "stemmer"
version = "1.2.0"
licenses = ["Apache 2.0"]
authors = ["Stephane.Carrez@gmail.com"]
maintainers = ["Stephane.Carrez@gmail.com"]
maintainers-logins = ["stcarrez"]
project-files = ["stemmer.gpr"]
tags = ["words", "stemmer"]
website = "https://gitlab.com/stcarrez/ada-stemmer"
long-description = """

[![Build Status](https://img.shields.io/jenkins/s/https/jenkins.vacs.fr/Bionic-Ada-Stemmer.svg)](https://jenkins.vacs.fr/job/Bionic-Ada-Stemmer/)
[![Test Status](https://img.shields.io/jenkins/t/https/jenkins.vacs.fr/Bionic-Ada-Stemmer.svg)](https://jenkins.vacs.fr/job/Bionic-Ada-Stemmer/)
[![codecov](https://codecov.io/gh/stcarrez/ada-stemmer/branch/master/graph/badge.svg)](https://codecov.io/gh/stcarrez/ada-stemmer)

The Ada Stemmer Library is a [stemming](https://en.wikipedia.org/wiki/Stemming) processor for several
natural languages.  It is based on the [Snowball compiler and stemming algorithms](https://snowballstem.org/)
which has been adapted to generate Ada code ([Snowball Ada](https://github.com/stcarrez/snowball/tree/ada-support)).
A stemming algorithm is used in natural language analysis to find
the base or root form of a word.  Such algorithm is specific to each natural language.
The [Porter Stemmer](https://tartarus.org/martin/PorterStemmer/) algorithm is specific to the English language
and will not work for French, Greek or Russian.

The Ada Stemmer Library integrates stemming algorithms for:
Arabic, Basque, Catalan, Danish, Dutch, English, Finnish, French, German, Greek,
Hindi, Hungarian, Indonesian, Irish, Italian, Lithuanian, Serbian, Nepali, Norwegian,
Portuguese, Romanian, Russian, Serbian, Spanish, Swedish, Tamil, Turkish.

Example of stemming:

|Language | Word          | Stem       |
|---------|---------------|------------|
|French   | chienne       | chien      |
|French   | affectionnait | affection  |
|English  | zealously     | zealous    |
|English  | transitional  | transit    |
|Greek    | ποσοτητα      | ποσοτητ    |
|Greek    | μνημειωδεσ    | μνημειωδ   |
|Russian  | ячменный      | ячмен      |
|Russian  | адом          | ад         |

"""

[gpr-externals]
BUILD = ["distrib", "debug", "optimize", "profile", "coverage"]
STEMMER_LIBRARY_TYPE = ["relocatable", "static", "static-pic"]
