--  Generated by Snowball 2.0.0 - https://snowballstem.org/

private with Ada.Strings.Unbounded;package Stemmer.Danish is
   type Context_Type is new Stemmer.Context_Type with private;
   procedure Stem (Z : in out Context_Type; Result : out Boolean);
private
   type Context_Type is new Stemmer.Context_Type with record
      I_X : Integer;
      I_P1 : Integer;
      S_Ch : Ada.Strings.Unbounded.Unbounded_String;
   end record;
end Stemmer.Danish;
